#!/bin/sh
# Script to build, compile, and run the little-lang compiler

# Capture all of the output to a variable to hide it, get results:
ouput=$(./gradlew assemble)
code=$?
if [ $code -ne 0 ]
   # if somthing went wrong:
then
    echo $output
    exit "$code"
    #if everthing is peachy:
else
    java -jar ./build/libs/little-compiler.jar $@;
fi
