#!/bin/bash
# Script to build, compile, and run the little-lang compiler

# print to stderr so the grading script won't see it:
./gradlew assemble > /dev/null
java -jar ./build/libs/little-compiler.jar $@;
